### ISSUE TITLE
`in` query parameter does not filter correctly

### ISSUE THREAD

**Issue by cptpiepmatz** [wisdom-oss/service-water-rights#1]
Requesting water rights using the `in` query parameter does not filter the water rights correctly.
Normally only the water rights in that area should be in the response.

## Example
`/api/water-rights/?in=03458&is_real=true`

**Comment by dr4hcu5-jan** [comment]
Calling other areas also result in a wrong response being returned on the server. Next step is to locally debug the microservice and it's returns to check for logic errors in the code.

**Comment by dr4hcu5-jan** [comment]
The debugging showed that the behavior is as expected with the given example.

However, when inspecting the SQL queries used to filter the location and reality state of a water right (which is also supplied in the example) the reality state filter also allows water right locations to be displayed which have *either* `true` _or_ `null` set as reality state.
```sql
-- name: filter-reality
real = $1 OR real IS NULL;
```

since this filter query is not in its own parenthesis, it allows every location matching the query parameters and _additionally_ all locations having `null` as reality state.
This query syntax bug is also included in the filter checking for active locations.
